### ISSUE TITLE
Some characters are bridged as HTML entities

### ISSUE THREAD

**Issue by xHire** [lagleki/Lojban-1Chat-Bridge#4]
The bot forwards some characters as HTML entities (e.g., `<` as `&lt;`). At least in the direction from Telegram to IRC.

**Comment by lagleki** [comment]
must be fixed via https://github.com/lagleki/Lojban-1Chat-Bridge/commit/a5aaafa230af5730bddaf957f0e42572ad42077c

**Comment by lagleki** [comment]
fixed
