### ISSUE TITLE
Markdown sent from messengers which don't support it (e.g. IRC, VK, etc.) should be escaped in messengers which do (e.g. Discord, Telegram, etc.)

### ISSUE THREAD

**Issue by lithiumjs** [lagleki/Lojban-1Chat-Bridge#84]
For example, "`_Hello_`" sent from IRC should not be visible as "_Hello_" (italic) on Discord.

**Comment by lagleki** [comment]
Probably just undercooked irc2html converter

**Comment by lagleki** [comment]
must be fixed via https://github.com/lagleki/Lojban-1Chat-Bridge/commit/557924c5abe31ef958c12d7983ed4282470fd564
deployed to Lojban chats
